#Install packages if not installed
installReqs <- function(package_name, bioc) {
  if (requireNamespace(package_name, quietly = TRUE) == FALSE) {
    if (bioc == FALSE)
      install.packages(package_name)
    else if (bioc == TRUE) #install using Bioconductor package manager
      BiocManager::install(package_name)
  }
}

#Install pacakges:
installReqs("BiocManager", bioc = FALSE)
installReqs("ggplot2", bioc = TRUE)
installReqs("Seurat", bioc = TRUE)
installReqs("stringr", bioc = TRUE)
installReqs("dplyr", bioc = TRUE)
installReqs("ggridges", bioc = TRUE)
installReqs("ggrepel", bioc = TRUE)
installReqs("ComplexHeatmap", bioc = TRUE)
installReqs("SingleCellExperiment", bioc = TRUE)
installReqs("ComplexHeatmap", bioc = TRUE)
installReqs("reshape2", bioc = TRUE)
installReqs("ggExtra", bioc = TRUE)
installReqs("SingleR", bioc = TRUE)
installReqs("Matrix", bioc = TRUE)
installReqs("patchwork", bioc = TRUE)
installReqs("SeuratDisk", bioc = TRUE)
installReqs("SeuratData", bioc = TRUE)
installReqs("SeuratWrappers", bioc = TRUE)
installReqs("scales", bioc = TRUE)
installReqs("scater", bioc = TRUE)
installReqs("cowplot", bioc = TRUE)
installReqs("circlize", bioc = TRUE)
installReqs("enrichplot", bioc = TRUE)
installReqs("Rmagic", bioc = TRUE)
installReqs("ggpmisc", bioc = TRUE)
installReqs("ggpmisc", bioc = TRUE)
installReqs("glmnet", bioc = TRUE)
installReqs("foreach", bioc = TRUE)
installReqs("ggrepel", bioc = TRUE)
installReqs("EnvStats", bioc = TRUE)
installReqs("tidyverse", bioc = TRUE)
installReqs("corrr", bioc = TRUE)
installReqs("igraph", bioc = TRUE)
installReqs("ggraph", bioc = TRUE)
installReqs("ggplot.multistats", bioc = TRUE)
installReqs("ggpubr", bioc = TRUE)
installReqs("survminer", bioc = TRUE)
installReqs("harmony", bioc = TRUE)
installReqs("knitr", bioc = TRUE)
installReqs("data.table", bioc = TRUE)
installReqs("kableExtra", bioc = TRUE)
installReqs("scRepertoire", bioc = TRUE)
installReqs("SCINA", bioc = TRUE)
installReqs("ProjecTILs", bioc = TRUE)
installReqs("SAVER", bioc = TRUE)
installReqs("future", bioc = TRUE)
